"""
Structured response models returned by Nova.
"""

from typing import Any, Literal

from pydantic import BaseModel, Field  # type: ignore


class ToolCall(BaseModel):
    """
    Represents a tool the agent wants to execute.
    """

    tool: str

    arguments: dict[str, Any] = Field(default_factory=dict)


class NovaResponse(BaseModel):
    """
    Structured response generated by Nova.
    """

    message: str

    updates: dict[str, Any] = Field(default_factory=dict)

    tool_calls: list[ToolCall] = Field(default_factory=list)

    conversation_stage: Literal[
        "COLLECTING_INFORMATION",
        "WAITING_FOR_CONFIRMATION",
        "COMPLETED",
    ] = "COLLECTING_INFORMATION"

    ready_for_confirmation: bool = False

    saved: bool = False